# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr = np.random.random(10)
print("Size of the array: ", arr.size)
print("Memory size of one array element in bytes: ", arr.itemsize)
print("Memory size of numpy array in bytes:", arr.size * arr.itemsize)

Size of the array:  10
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
arr = np.zeros(10,int)
arr[4]=1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
arr = np.random.random(10)
print(arr)
res_arr = np.flip(arr)
print(res_arr)

[0.08152162 0.56699917 0.0034234  0.95972791 0.84687437 0.2028799
 0.48967739 0.5871537  0.77632789 0.57921579]
[0.57921579 0.77632789 0.5871537  0.48967739 0.2028799  0.84687437
 0.95972791 0.0034234  0.56699917 0.08152162]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
np.random.random((3,3,3))

array([[[0.69743251, 0.50673908, 0.76167024],
        [0.83557162, 0.22759154, 0.05459078],
        [0.83412103, 0.46904492, 0.30984069]],

       [[0.82367277, 0.11606047, 0.11204105],
        [0.1160537 , 0.01812811, 0.10330495],
        [0.40735812, 0.03018263, 0.19687778]],

       [[0.37956539, 0.3368907 , 0.09992186],
        [0.61602243, 0.45691579, 0.8877924 ],
        [0.76557334, 0.55323446, 0.69519182]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
arr = np.random.random((10,10))
print(arr)
print(arr.max(axis=0)) # aggregate along the row
print(arr.max(axis=1)) # aggregate along the columns

print(arr.min(axis=0)) # aggregate along the row
print(arr.min(axis=1)) # aggregate along the columns

[[0.54386648 0.39758245 0.67481942 0.2113744  0.78024154 0.67563409
  0.52572742 0.58845166 0.28977445 0.15543583]
 [0.84026694 0.85322639 0.21196161 0.25867635 0.34226353 0.01900784
  0.6852015  0.67213742 0.58636322 0.77811263]
 [0.17978045 0.03247295 0.40894895 0.87845971 0.64163142 0.23350528
  0.2514732  0.05016373 0.02492518 0.71699957]
 [0.41552926 0.73037451 0.54951987 0.86772755 0.65441416 0.48127154
  0.7431727  0.06631535 0.22192068 0.5933664 ]
 [0.90033246 0.09877307 0.97061834 0.33688186 0.21348249 0.46118836
  0.27297868 0.67856247 0.6012767  0.68121119]
 [0.55352047 0.48546799 0.94102291 0.48837787 0.578448   0.70787306
  0.50397348 0.9292866  0.74095226 0.46687079]
 [0.49664568 0.06771906 0.82159335 0.93986768 0.45271307 0.40256853
  0.35992785 0.32991364 0.00702288 0.0444115 ]
 [0.30719358 0.03430051 0.51665797 0.42088207 0.30103122 0.35363855
  0.22853214 0.43705818 0.933159   0.92642792]
 [0.82164632 0.54534743 0.70720541 0.33822412 0.79961822 0.22760312
  0.69063759

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [12]:
arr = np.random.random(30)
print(arr)
print("Mean: ", arr.mean())

[0.28019331 0.6821288  0.88337644 0.85556541 0.16256593 0.94197794
 0.02746312 0.46448845 0.73858613 0.33123233 0.73996798 0.67222079
 0.58651727 0.23213319 0.55332404 0.84239155 0.30662505 0.09048331
 0.85368697 0.91212025 0.34033666 0.32045401 0.01546002 0.02967686
 0.06507771 0.18807411 0.00980022 0.88404432 0.69070806 0.07807752]
Mean:  0.45929192576455613


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((5,5))
print("Before:\n", arr)
arr[1:-1, 1:-1] = 0
print("After:\n", arr)

Before:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
After:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [36]:
arr = np.diag(1+np.arange(4), k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [49]:
arr = np.ones((8,8), int)
arr[::2, ::2] = 0
arr[1::2, 1::2] = 0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [50]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [53]:
arr = np.array([[0,1], [1,0]])
arr = np.tile(arr, (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [55]:
arr = np.random.random((5,5))
arr_max, arr_min = arr.max(), arr.min()
arr = (arr-arr_min)/(arr_max-arr_min)
print (arr)

[[0.22004832 0.52856261 0.21529092 0.15849569 0.34046315]
 [0.77353105 0.5649828  0.93956079 0.95368848 0.64665642]
 [1.         0.63106473 0.25469195 0.5828481  0.37968546]
 [0.78160973 0.         0.29907245 0.70490883 0.34634584]
 [0.15903434 0.38456773 0.54304366 0.37955512 0.72614347]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [58]:
arr = np.dot(np.ones((5,3), int), np.ones((3,2), int))
arr

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [60]:
ar = np.arange(15)
ar[(3 < ar) & (ar < 8)] *= -1
ar

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

## 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [80]:
arr1 = np.array([0, 1, 2, 3, 4])
arr2 = [1, 3, 4]
  
print(np.intersect1d(arr1, arr2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
No

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [84]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)
today     = np.datetime64('today', 'D')
print("Today: ", today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Yestraday:  2022-10-12
Today:  2022-10-13
Tomorrow:  2022-10-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [85]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
array = np.random.random(10)
print(array)
array.sort()
print(array)

[0.62769375 0.10747179 0.24379933 0.26701602 0.71704465 0.8778888
 0.21059429 0.17498005 0.27410402 0.06090479]
[0.06090479 0.10747179 0.17498005 0.21059429 0.24379933 0.26701602
 0.27410402 0.62769375 0.71704465 0.8778888 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)